### ISSUE TITLE
Unclear inputs required

### ISSUE THREAD

**Issue by emullier** [bids-apps/giga_connectome#171]
In the context of the review [(https://github.com/openjournals/joss-reviews/issues/7061 )], I am trying to run the giga connectome on one publicly available subject ([(https://zenodo.org/records/5790821)])

It is not clear to me what inputs I should use to run the giga_connectome

I followed the following steps:

1. I downloaded the subject, passed it through the bids validator (1.14.0) without any error

2. I ran fmriprep (via docker version  24.1.0rc0), with all my fmriprep outputs generated in my derivatives directory
![image](https://github.com/user-attachments/assets/244f16ef-c286-427b-87e2-8ba1a4b04c43)

3. Finally I tried to run giga_connectome via this command line
```
docker run -it --rm -v  /home/localadmin/DATA/ds-sample_GigaConnectome/derivatives:/bids_dir -v  /home/localadmin/DATA/ds-sample_GigaConnectome/derivatives/giga_connectome:/out bids/giga_connectome bids_dir out  participant --participant_label 01 
```

This is not clear for me if bids_dir should be my derivatives with the fmriprep output or my original bids directory?
I tried both but in both case I get the same error which seems to be a bids issue

````
          INFO     Indexing BIDS directory:                      workflow.py:66
                            bids_dir                                            
Traceback (most recent call last):
  File "/usr/local/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/run.py", line 127, in main
    workflow(args)
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/workflow.py", line 81, in workflow
    subj_data, _ = utils.get_bids_images(
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/utils.py", line 81, in get_bids_images
    subj_data = {
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/utils.py", line 82, in <dictcomp>
    dtype: layout.get(**layout_get_kwargs, **query)
  File "/usr/local/lib/python3.9/site-packages/bids/layout/layout.py", line 629, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'desc' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.

`````

**Comment by htwangtw** [comment]
@emullier 
Thanks for opening the issue! 

I see that you are using the latest fMRIPrep release candidate version, which is not tested on.
All the developments of the software is aiming to support fMRIPrep LTS versions, sorry that this is not clear in our documentations. If you can preprocess the subject with the [latest LTS version](https://fmriprep.org/en/stable/changes.html#id1) and report back, that would be extremely helpful.

To help me debug this specific message, can you print out the tree of `sub-01/`? This will help me to understand if this is a issue stemmed from a new version or a bug...

**Comment by Remi-Gau** [comment]
- I think that this PR may fix that: https://github.com/bids-apps/giga_connectome/pull/174

I was getting the same "desc" not recognized issue

**Comment by htwangtw** [comment]
@emullier Can you verify this issue is resolved with the current main branch, you pull the unstable version of the container to verify this
`docker pull bids/giga_connectome:unstable`
Further more we added more detailed documentations in #205
