### ISSUE TITLE
Issue with templateflow dir not found

### ISSUE THREAD

**Issue by emullier** [bids-apps/giga_connectome#172]
Following my issue 
Unclear inputs required #171 , I tried in parallel to run on my subject the giga_connectome not via docker but via github installation running this command

```` 
giga_connectome /home/localadmin/DATA/ds-sample_GigaConnectome /home/localadmin/DATA/ds-sample_GigaConnectome/derivatives/ participant --participant_label 01 
````

for which I get an error which seems to be related to templateflow_dir not found.

I checked I have templateflow installed on my computer (version 0.8.1)

And I have tried to export the path in my ubuntu terminal using this command 
````
export TEMPLATEFLOW_HOME=/home/localadmin/.cache/templateflow
````
But it does not seem as it solved my error

Error

````
{'bids_dir': PosixPath('/home/localadmin/DATA/ds-sample_GigaConnectome'), 'output_dir': PosixPath('/home/localadmin/DATA/ds-sample_GigaConnectome/derivatives'), 'analysis_level': 'participant', 'participant_label': ['01'], 'work_dir': PosixPath('/opt/work'), 'atlas': 'MIST', 'denoise_strategy': 'simple', 'standardize': 'zscore', 'smoothing_fwhm': 5.0, 'reindex_bids': False, 'bids_filter_file': None, 'calculate_intranetwork_average_correlation': False}
{'name': 'MIST', 'parameters': {'atlas': 'BASC', 'template': 'MNI152NLin2009bAsym', 'resolution': '03', 'suffix': 'dseg'}, 'desc': [7, 12, 20, 36, 64, 122, 197, 325, 122, 444], 'templateflow_dir': None}
Traceback (most recent call last):
  File "/opt/fsl/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/fsl/lib/python3.11/site-packages/giga_connectome/run.py", line 111, in main
    workflow(args)
  File "/opt/fsl/lib/python3.11/site-packages/giga_connectome/workflow.py", line 31, in workflow
    atlas = load_atlas_setting(args.atlas)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fsl/lib/python3.11/site-packages/giga_connectome/atlas.py", line 65, in load_atlas_setting
    p = templateflow.api.get(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fsl/lib/python3.11/site-packages/templateflow/conf/__init__.py", line 65, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fsl/lib/python3.11/site-packages/templateflow/api.py", line 112, in get
    raise Exception("No results found")
Exception: No results found


````

**Comment by htwangtw** [comment]
The reason is that the container image has downloaded all the atlases used for the app and a direct installation will require extra steps for set ups. 

If the templateflow directory is downloaded with all the defaults, can you try to run this command:

```bash
giga_connectome /home/localadmin/DATA/ds-sample_GigaConnectome \
    /home/localadmin/DATA/ds-sample_GigaConnectome/derivatives/ \
    participant \
    --participant_label 01 \
    --atlas Schaefer2018
```

Since this is not the intended use case so I did not document it very well. 
I will add extra instruction on contributor guide, and also direct users if they really want a bare bone installation.

**Comment by htwangtw** [comment]
This has been further clarified by the updated documentaton
