### ISSUE TITLE
[BUG] unknown atlas does not give the expected error

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/giga_connectome#173]
### What version of the bids app were you using?

latest 

### Describe your problem in detail.

tried a dummy atlas that should fail

### What command did you run?

tried to run with atlas `foo`

```bash
~/datalad/datasets.datalad.org/openneuro-derivatives/ds000001-fmriprep on main✔ 24-09-19 - 17:41:01
╰─(base) ⠠⠵ docker run -it --rm -v $PWD:/bids -v ~/tmp:/output  bids/giga_connectome:latest /bids /output participant --verbosity 3 --atlas foo           
[15:41:15] INFO     {'bids_dir': PosixPath('/bids'), 'output_dir': PosixPath('/output'),                  workflow.py:37
                    'analysis_level': 'participant', 'participant_label': None, 'work_dir':                             
                    PosixPath('/code/work'), 'atlas': 'foo', 'denoise_strategy': 'simple',                              
                    'smoothing_fwhm': 5.0, 'reindex_bids': False, 'bids_filter_file': None,                             
                    'calculate_intranetwork_average_correlation': False, 'verbosity': [3]}                              
Traceback (most recent call last):
  File "/usr/local/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/run.py", line 127, in main
    workflow(args)
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/workflow.py", line 53, in workflow
    atlas = load_atlas_setting(args.atlas)
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/atlas.py", line 64, in load_atlas_setting
    atlas_config = _check_altas_config(atlas)
  File "/usr/local/lib/python3.9/site-packages/giga_connectome/atlas.py", line 192, in _check_altas_config
    with open(config_path, "r") as file:
UnboundLocalError: local variable 'config_path' referenced before assignment
```

### Describe what you expected.

an error that says "atlas unknown"

**Comment by Remi-Gau** [comment]
OK tested on main and the error is not there anymore

**Comment by Remi-Gau** [comment]
or at least the error message makes more sense
